### ISSUE TITLE
Dependency injection in js

### ISSUE THREAD

**Issue by steamrunner4** [JSBelgrade/cfp#12]
Ivan Stanojevic
stanojevic.ivan.work@gmail.com

Abstract:
- what is DI
- why would you use
- how to implement DI => load modules in files, object map, parse functions, instantiate
- problems
- live example
- Q&A

Preferred language:
Serbian

Duration:
30-60min

Group:
small

Why:
To quote my wife: "Da zbrise od zene" :D

**Comment by min-che** [comment]
:+1:

**Comment by stojanovic** [comment]
http://www.meetup.com/JS-Belgrade-Meetup/events/230457795/
