### ISSUE TITLE
Introduction to React with Redux

### ISSUE THREAD

**Issue by raleksandar** [JSBelgrade/cfp#13]
### Talk

**Topic:** Introduction to React with Redux
**Desc:** Introduction to React.js, Flux architecture and how to use React with Redux to build SPAs.
**Preferred language:** Serbian
**Duration:** 30-60 minutes
**Preferred size:** Small meetup
**When:** May 2016.
### Personal info

**Name:** Aleksandar Ružičić
**Email:** aleksandar@ruzicic.info
**About:** End-to-end developer, but mostly focused on JavaScript

**Comment by min-che** [comment]
👍 

nadam se da ovo neću propustiti 😃
