### ISSUE TITLE
Introduction to React Native

### ISSUE THREAD

**Issue by BugiDev** [JSBelgrade/cfp#15]
Talk

Topic: Introduction to React Native
Desc: Introduction to React Native + tips and tricks about atomic design, animations, performance and updating
Preferred language: Serbian
Duration: 30-60 minutes
Preferred size: Medium to large meetup
When: 18. Jun 2016.

Personal info

Name: Bogdan Begović
Email: bogdanbegovic@gmail.com
About: Software engineer with a thing for JS, UX and mobile
LinkedIn: https://rs.linkedin.com/in/bogdan-begovic-84186848

**Comment by Lazzaro83** [comment]
yes

**Comment by stojanovic** [comment]
http://www.meetup.com/JS-Belgrade-Meetup/events/231867157/
