### ISSUE TITLE
Introduction to Elm

### ISSUE THREAD

**Issue by moljac024** [JSBelgrade/cfp#17]
Talk

Topic: Introduction to Elm
Desc: Introduction to functional programming and the Elm langage, along with tips how to gradually introduce Elm into an existing JS codebase
Preferred language: Serbian or English
Duration: 30-60 minutes
Preferred size: Small to medium meetup
When: December 2016

Personal info

Name: Bojan Matić
Email: matic.bojan@gmail.com
About: Polyglot developer, currently focused on front-end and doing mostly React.js
Twitter: @moljac024

**Comment by stojanovic** [comment]
Was on Meetup #23: https://www.meetup.com/JS-Belgrade-Meetup/events/237189299/
