### ISSUE TITLE
Koa

### ISSUE THREAD

**Issue by stojanovic** [JSBelgrade/cfp#2]
### Talk

**Topic:** Koa framework
**Desc:** Practical example how to build an app with Koa, how to use async/await with Koa and how to build a simple middleware.
**Preferred language:** Serbian or English
**Duration:** 30-60 minutes
**Preferred size:** Small meetup
**When:** Whenever.
### Personal info

**Name:** Slobodan Stojanović
**Email:** slobodan@cloudhorizon.com
**About:** CTO of Cloud Horizon, programmer mostly focused on JavaScript.
**Twitter:** @slobodan_

---

:+1: if you want to hear about this topic, :-1: if you don't (it's ok if you don't want, no hard feelings ofc :))

**Comment by gorangajic** [comment]
:+1:

**Comment by simalexan** [comment]
:+1:

**Comment by aysbg** [comment]
:+1:

**Comment by radosavljevic** [comment]
:+1:

**Comment by tju** [comment]
:+1:
