### ISSUE TITLE
Pouch DB

### ISSUE THREAD

**Issue by stojanovic** [JSBelgrade/cfp#3]
### Talk

**Topic:** Pouch DB hands-on 
**Desc:** Practical example how to use Pouch DB in the browser and in node.js and how to sync it with remote Pouch/Couch DB.
**Preferred language:** Serbian or English
**Duration:** 30-60 minutes
**Preferred size:** Small meetup
**When:** Whenever.
### Personal info

**Name:** Slobodan Stojanović
**Email:** slobodan@cloudhorizon.com
**About:** CTO of Cloud Horizon, programmer mostly focused on JavaScript.
**Twitter:** @slobodan_

---

:+1: if you want to hear about this topic, :-1: if you don't (it's ok if you don't want, no hard feelings ofc :))

**Comment by gorangajic** [comment]
:+1:

**Comment by simalexan** [comment]
:+1:

**Comment by aysbg** [comment]
:+1:

**Comment by radosavljevic** [comment]
:+1:

**Comment by tju** [comment]
:+1:
