### ISSUE TITLE
PDF.js & its challenges

### ISSUE THREAD

**Issue by simalexan** [JSBelgrade/cfp#4]
## Talk

**Topic:** PDF.js & its highlighting / scaling challenges
**Desc:** Displaying PDFs in your web applications and its highlighting with scaling challenges
**Preferred language:** Serbian or English
**Duration:** 30-60 minutes
**Preferred size:** Small meetup
**When:** Any time
### Personal info

**Name:** Aleksandar Simović
**Email:** alexander.simovic@gmail.com
**About:** Software engineer, rubber ducker
**Twitter:** @simalexan

:+1: if you want to hear about this topic, :-1: if you don't (it's ok if you don't want, no hard feelings ofc :))

**Comment by stojanovic** [comment]
👍

**Comment by gorangajic** [comment]
:+1:

**Comment by aysbg** [comment]
:+1:

**Comment by radosavljevic** [comment]
:+1:

**Comment by min-che** [comment]
:+1:

**Comment by tju** [comment]
:+1:
