### ISSUE TITLE
velocity-react

### ISSUE THREAD

**Issue by radosavljevic** [JSBelgrade/cfp#5]
### **Talk**

**Topic:** UI using VelocityReact library
**Desc:** Demo web app showing the power of React.js and VelocityReact library.
**Preferred language:** Serbian or English
**Duration:** 30-60 minutes
**Preferred size:** Small meetup
**When:** Whenever.
### **Personal info**

**Name:** Slobodan Radosavljević
**Email:** slobodanmeister@gmail.com
**About:** Freelancer, Frontend developer, JS.
**Twitter:** @SlobodanRad

**Comment by stojanovic** [comment]
:+1:

**Comment by gorangajic** [comment]
:+1:

**Comment by tju** [comment]
:+1:

**Comment by stojanovic** [comment]
@radosavljevic je l' bi još uvek pričao o ovom? Pitam zato što čistim malo CFP :)

**Comment by radosavljevic** [comment]
@stojanovic :) Davno beše pa bih radije o nekim stvarima koje zapravo koristim, npr react, typescript, redux, middleware. Da li to zanima ljude?

**Comment by stojanovic** [comment]
Prijavi CFP kad budeš hteo :) Siguran sam da zanima. Posebno typescript i stvari koje nisu već bile.

Zatvaram ovaj i čekam naredni uskoro :)

**Comment by radosavljevic** [comment]
:) 👍
