### ISSUE TITLE
Global Day of Coderetreat (Belgrade) - November 14, 2015

### ISSUE THREAD

**Issue by tju** [JSBelgrade/cfp#6]
Topic: **Global Day of Coderetreat (Belgrade) - November 14, 2015**
 a day to celebrate passion and software craftsmanship
**Preferred language:** Serbian or English
**Preferred size:** Small meetup (up to 20)

**Structure** (http://coderetreat.org/facilitating/structure-of-a-coderetreat)
Coderetreat has an established, time-tested format that is optimized for focused practice.

**Problem:** Conway's Game of Life
**Length of Session:** 45 minutes
**Duration:** 8.30am to 5 or 6pm
- Pair-programming is necessary, as the knowledge transfer contained in that activity is essential to the practice
- Prefer using Test-Driven Development (TDD)
- After each session, pairs should be swapped
- After each session, code must be deleted, not put in a branch, not stashed, just deleted with no trace left

more info: 
http://globalday.coderetreat.org/

**Personal info**
Name: Ivan Ćurković
Email: ivan.curkovic@gmail.com
About: Software Developer 
Twitter: @ivan_curkovic

**Comment by stojanovic** [comment]
:+1:

**Comment by stojanovic** [comment]
@tju it's Saturday, we can definitely try this in November. I just need to check if I am in Belgrade that week.

**Comment by dulerock** [comment]
:thumbsup:

**Comment by aysbg** [comment]
:+1:

**Comment by min-che** [comment]
:+1:

**Comment by simalexan** [comment]
:+1:

**Comment by rubystream** [comment]
:+1:

**Comment by stojanovic** [comment]
Done: http://www.jsbelgrade.org/global-day-of-coderetreat-2015-belgrade-serbia/
Thanks @tju! :)
