### ISSUE TITLE
IoT in JS for fun and profit

### ISSUE THREAD

**Issue by rubystream** [JSBelgrade/cfp#7]
Talk

Topic: _Internet of Things_ using **JavaScript** for fun and profit
Desc: Presentation on how to use JavaScript to build IoT related projects. Mostly fun with some potential for profit :-)
Preferred language: Serbian or English
Duration: up to 60 minutes
Preferred size: any
When: 28 Nov 2015 
Personal info

Name: Dejan Dimic
Email: dejan.dimic@gmail.com
About: JavaScript advocate :-)
Twitter: @dejan_dimic

**Comment by simalexan** [comment]
:+1:

**Comment by stojanovic** [comment]
:+1:

**Comment by gorangajic** [comment]
:+1: :+1: :+1:

**Comment by min-che** [comment]
:+1:

**Comment by vedraan** [comment]
u to mi treba :+1:

**Comment by marko-ciric** [comment]
+1

**Comment by tju** [comment]
:+1:

**Comment by radosavljevic** [comment]
:+1:

**Comment by stojanovic** [comment]
http://www.meetup.com/JS-Belgrade-Meetup/events/226647168/
Thanks!
