### ISSUE TITLE
JS Bots - Slack, Hubot...

### ISSUE THREAD

**Issue by stojanovic** [JSBelgrade/cfp#8]
### Talk

**Topic:** JS Bots - Slack, Hubot... 
**Desc:** Practical example how to create Slack and Hubot bots.
**Preferred language:** Serbian or English
**Duration:** 30-60 minutes
**Preferred size:** Small meetup
**When:** Whenever.
### Personal info

**Name:** Slobodan Stojanović
**Email:** slobodan@cloudhorizon.com
**About:** Programmer, mostly focused on JavaScript.
**Twitter:** @slobodan_

---

:+1: if you want to hear about this topic, :-1: if you don't (it's ok if you don't want, no hard feelings ofc :))

**Comment by min-che** [comment]
:+1:

**Comment by simalexan** [comment]
:+1:
